# This deployment is used to confirm connectivity across the cluster
apiVersion: v1
kind: Service
metadata:
  labels:
    service: busybox
  name: busybox
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    service: busybox
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: busybox
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      service: busybox
  template:
    metadata:
      labels:
        service: busybox
    spec:
      containers:
      - image: radial/busyboxplus:curl
      #- image: hypriot/armhf-busybox
        name: busybox
        imagePullPolicy: Always
        command:
        - sleep
        - "3600"
        envFrom:
        - configMapRef:
            name: db-env
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
      restartPolicy: Always
      # nodeSelector:
      #   arch: armv7
      #  # Allow deployment to run on Raspberry pi 4
      # tolerations:
      # - key: "arch"
      #   operator: "Equal"
      #   value: "armv7"
      #   effect: "NoExecute"