apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: ingest-consumer
  name: ingest-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ingest-consumer
  template:
    metadata:
      labels:
        service: ingest-consumer
    spec:
      containers:
      - image: badrmoh/ingest-consumer:latest
        name: ingest-consumer
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_SERVICE
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_ADVERTISED_HOST_NAME
      restartPolicy: Always
      # nodeSelector:
      #   arch: armv7
      #  # Allow deployment to run on Raspberry pi 4
      # tolerations:
      # - key: "arch"
      #   operator: "Equal"
      #   value: "armv7"
      #   effect: "NoExecute"

