apiVersion: v1
kind: ConfigMap
data:
  KAFKA_ADVERTISED_HOST_NAME: "kafka"
  KAFKA_CREATE_TOPICS: "locations:1:1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper"
  KAFKA_TOPIC: "locations"
metadata:
  name: kafka-env