apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka
  name: kafka
spec:
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
    tag: wurstmeister
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      tag: wurstmeister
  template:
    metadata:
      labels:
        app: kafka
        tag: wurstmeister
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_ADVERTISED_HOST_NAME
        - name: KAFKA_CREATE_TOPICS
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_CREATE_TOPICS
        - name: KAFKA_ZOOKEEPER_CONNECT
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_ZOOKEEPER_CONNECT
