apiVersion: v1
kind: Service
metadata:
  labels:
    service: zookeeper
  name: zookeeper
spec:
  ports:
  - port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    app: zookeeper
    tag: wurstmeister
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    service: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
      tag: wurstmeister
  template:
    metadata:
      labels:
        app: zookeeper
        tag: wurstmeister
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper
        ports:
        - containerPort: 2181