name: Locations API docker image
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
    paths:
      - 'microservices/locations-api/**'
      - '.github/workflows/locations-api-docker.yaml'
    workflow_dispatch:
jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    environment: 
          name: test
    steps:
      - uses: actions/checkout@v2
      
      # we need qemu and buildx so we can build multiple platforms later
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  
            
      - name: Build push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: microservices/locations-api
          file: microservices/locations-api/Dockerfile
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          # don't push during a pull_request, only build
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/locations-api:latest
          push: ${{ github.event_name != 'pull_request' }}
          
      - name: Show image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
